/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

/**
 *
 * @author aloma
 */

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;




   
 
public class FirstFrame extends javax.swing.JFrame{

    
    String name ;
    int counter = 0;
    private static final String Server_IP="localhost";
    private static final int Server_port=9090;
    WaitingRoom frame = new WaitingRoom();
    private Socket socket;
    private BufferedReader in;
    private  PrintWriter out;
    ServerConnection servcon;
    /**
     * Creates new form FirstFrame
     */
    public FirstFrame() {
        initComponents();
        playButton.setVisible(false);
        try{
         socket = new Socket (Server_IP,Server_port);
         in= new BufferedReader (new InputStreamReader(socket.getInputStream())); 
         out=new PrintWriter(socket.getOutputStream(),true);
         
        } catch (Exception e){
                  e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConnectedList = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("connect");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setMargin(new java.awt.Insets(15, 15, 15, 15));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 100, 30));

        jTextField1.setBackground(new java.awt.Color(228, 228, 253));
        jTextField1.setFont(new java.awt.Font("SimSun", 1, 17)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 240, 30));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Enter your name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 210, -1));

        playButton.setBackground(new java.awt.Color(153, 153, 255));
        playButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22)); // NOI18N
        playButton.setForeground(new java.awt.Color(255, 255, 255));
        playButton.setText("Play");
        playButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 160, 40));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        ConnectedList.setEditable(false);
        ConnectedList.setBackground(new java.awt.Color(204, 204, 255));
        ConnectedList.setColumns(20);
        ConnectedList.setLineWrap(true);
        ConnectedList.setRows(5);
        ConnectedList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jScrollPane1.setViewportView(ConnectedList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 240, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/game-page.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
        //send request to server to see the ability for joining room
        out.println("tryToJoinRoom");
        
    }//GEN-LAST:event_playButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         name = jTextField1.getText();
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, "please enter your name to connect");
        }
        else{
             try {
                 connectToServer(name);
             } catch (IOException ex) {
                 Logger.getLogger(FirstFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
          jTextField1.setEditable(false);
        }
            
        


        
        
    }//GEN-LAST:event_jButton2ActionPerformed
private void connectToServer(String clientName) throws IOException{
        
          try{
              //Establish the connection to server
              PrintWriter out=new PrintWriter(socket.getOutputStream(),true);

              System.out.println("Connect with server");
              //send client name to server
              out.println(clientName);
              
              servcon=new ServerConnection(socket , this , frame);
             
              new Thread (servcon).start(); 
            
                     // out.println(name); 
                          playButton.setVisible(true);

              } catch (Exception e){
                  e.printStackTrace();
              }
          }

public void waitingRoomIsFull(){
        JOptionPane.showMessageDialog(this, "you can't play now! we are sorry");
    }
public void canJoinWaitingRoom(){
         playButton.setVisible(true);

}
        
 
public void ClientUpdated(String names){
    System.out.println("Updating clients names: " + names);
     ConnectedList.setText(names);
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ConnectedList;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
